#!/usr/bin/env -P /usr/local/bin:/opt/homebrew/bin bash
#/usr/local/bin/brew-clean

boottime=$(sysctl -n kern.boottime | sed -e 's/.* sec *= *\([0-9][0-9]*\).*/\1/')
# shellcheck disable=SC2016
output='map({name:.name, installed:.installed | max_by(.time).time})[] | select(.installed > ($boottime|tonumber)) | .name'
count=$(tr -dc '/' <<< "$HOMEBREW_CELLAR/" | wc -c)

function label_to_pid(){
    pid=$(launchctl print "gui/$UID/homebrew.mxcl.$1" | awk '/pid = /{print $NF}')
    if [ -z "$pid" ]; then
        pid=$(launchctl print "system/homebrew.mxcl.$1" | awk '/pid = /{print $NF}')
    fi
    echo "$pid"
}

function pid_to_seconds_up(){
    \ps -oetime= -p "$1" | tr '-' ':' | awk -F: '{ total=0; m=1; } { for (i=0; i < NF; i++) {total += $(NF-i)*m; m *= i >= 2 ? 24 : 60 }} {print total}'
}

function was_restarted(){
    pid=$(label_to_pid $1)
    seconds=$(pid_to_seconds_up "$pid")
    now=$(date '+%s')
    uptime=$(\bc -l <<< "scale=4; $now - $boottime")
    test "$seconds" -lt "$uptime"
}

brew cleanup -n | grep -Fe "$HOMEBREW_CELLAR/" -e 'would free' | tee /dev/stderr | cut -d/ -f$((count + 1)) | grep -Fxf <(brew list --pinned) | sort -u | xargs brew info --json --formulae | jq --arg boottime "$boottime" --raw-output "$output" | xargs echo "==> pinned formulae updated since last reboot:"
