#!/usr/bin/env -P /usr/local/bin:/opt/homebrew/bin bash
#/usr/local/bin/brew-clean

boottime=$(sysctl -n kern.boottime | sed -e 's/.* sec *= *\([0-9][0-9]*\).*/\1/')
# shellcheck disable=SC2016
output='map({name:.name, installed:.installed | max_by(.time).time})[] | select(.installed > ($boottime|tonumber)) | .name'
count=$(tr -dc '/' <<< "$HOMEBREW_CELLAR/" | wc -c)

brew cleanup -n | grep -Fe "$HOMEBREW_CELLAR/" | tee /dev/stderr | cut -d/ -f$((count + 1)) | grep -Fxf <(brew list --pinned) | sort -u | xargs brew info --json --formulae | jq --arg boottime "$boottime" --raw-output "$output" | xargs echo "pinned formulae found:"
